<?php
/*
 * AUTOGENERATED CODE - DO NOT EDIT!
 *
 * This base class was generated by the Trellis library and
 * must not be modified manually. Any modifications to this
 * file will be lost upon triggering the next automatic
 * class generation.
 *
 * If you are looking for a place to alter the behaviour of
 * the 'User' type please see the skeleton
 * class 'UserType'. Modifications to the skeleton
 * file will prevail any subsequent class generation runs.
 *
 * To define new attributes or adjust existing attributes and their
 * default options modify the schema definition file of
 * the 'User' type.
 *
 * @see https://github.com/honeybee/trellis
 */

namespace Honeybee\SystemAccount\User\Projection\Standard\Base;

use Trellis\Common\Options;
use Workflux\StateMachine\StateMachineInterface;
use Honeybee\SystemAccount\User\Projection\Standard\Base;
use Honeybee\Projection\ProjectionType;

/**
 * Serves as the base class to the 'User' type skeleton.
 */
abstract class UserType extends ProjectionType
{
    /**
     * StateMachineInterface $workflow_state_machine
     */
    protected $workflow_state_machine;

    /**
     * Creates a new 'UserType' instance.
     *
     * @param StateMachineInterface $workflow_state_machine
     */
    public function __construct(StateMachineInterface $workflow_state_machine)
    {
        $this->workflow_state_machine = $workflow_state_machine;

        parent::__construct(
            'User',
            [
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'username',
                    $this,
                    array(
                        'mandatory' => true,
                        'min_length' => 1,
                        'max_length' => 50,
                    )
                ),
                new \Trellis\Runtime\Attribute\Email\EmailAttribute(
                    'email',
                    $this,
                    array(
                        'mandatory' => true,
                    )
                ),
                new \Trellis\Runtime\Attribute\Url\UrlAttribute(
                    'url',
                    $this,
                    array(
                        'allowed_schemes' => array(
                            'http',
                            'https',
                        ),
                    )
                ),
                new \Trellis\Runtime\Attribute\Choice\ChoiceAttribute(
                    'role',
                    $this,
                    array(
                        'mandatory' => true,
                        'min_length' => 1,
                        'max_length' => 255,
                        'allowed_values' => array(
                            'administrator' => 'administrator',
                            'test-role-additiv' => 'test-role-additiv',
                            'test-two' => 'test-two',
                        ),
                    )
                ),
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'firstname',
                    $this,
                    array(
                        'max_length' => 100,
                    )
                ),
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'lastname',
                    $this,
                    array(
                        'max_length' => 100,
                    )
                ),
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'password_hash',
                    $this,
                    array(
                        'min_length' => 50,
                        'max_length' => 100,
                    )
                ),
                new \Trellis\Runtime\Attribute\Integer\IntegerAttribute(
                    'birth_year',
                    $this,
                    array(
                        'min_value' => 1900,
                        'max_value' => 2020,
                    )
                ),
                new \Trellis\Runtime\Attribute\Float\FloatAttribute(
                    'hourly_rate',
                    $this,
                    array(
                        'min_value' => '8.5',
                        'max_value' => 120,
                    )
                ),
                new \Trellis\Runtime\Attribute\Textarea\TextareaAttribute(
                    'biography',
                    $this,
                    array(
                        'max_length' => 1000,
                    )
                ),
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'auth_token',
                    $this,
                    array(
                        'max_length' => 40,
                    )
                ),
                new \Trellis\Runtime\Attribute\Timestamp\TimestampAttribute(
                    'token_expire_date',
                    $this,
                    array(
                        'format_native' => 'Y-m-d\\TH:i:s.uP',
                    )
                ),
                new \Trellis\Runtime\Attribute\TextList\TextListAttribute(
                    'tags',
                    $this,
                    array(
                        'max_count' => 50,
                        'min_length' => 1,
                        'max_length' => 40,
                    )
                ),
                new \Trellis\Runtime\Attribute\ImageList\ImageListAttribute(
                    'images',
                    $this,
                    array(
                        'max_count' => 50,
                    )
                ),
                new \Trellis\Runtime\Attribute\EmbeddedEntityList\EmbeddedEntityListAttribute(
                    'comments',
                    $this,
                    array(
                        'entity_types' => array(
                            '\\Honeybee\\SystemAccount\\User\\Projection\\Standard\\Embed\\CommentType',
                        ),
                    )
                ),
                new \Trellis\Runtime\Attribute\EntityReferenceList\EntityReferenceListAttribute(
                    'friends',
                    $this,
                    array(
                        'entity_types' => array(
                            '\\Honeybee\\SystemAccount\\User\\Projection\\Standard\\Reference\\FriendType',
                        ),
                    )
                ),
            ],
            new Options(
                array(
                'vendor' => 'Honeybee',
                'package' => 'SystemAccount',
                'is_hierarchical' => true,
            )
            )
        );
    }

    /**
     * Returns an (immutable) state-machine instance responseable for controlling an entity's workflow.
     *
     * @return StateMachineInterface
     */
    public function getWorkflowStateMachine()
    {
        return $this->workflow_state_machine;
    }

    /**
     * Returns the EntityInterface implementor to use when creating new entities.
     *
     * @return string Fully qualified name of an EntityInterface implementation.
     */
    public static function getEntityImplementor()
    {
        return '\\Honeybee\\SystemAccount\\User\\Projection\\Standard\\User';
    }
}
