<?php
/*
 * AUTOGENERATED CODE - DO NOT EDIT!
 *
 * This base class was generated by the Trellis library and
 * must not be modified manually. Any modifications to this
 * file will be lost upon triggering the next automatic
 * class generation.
 *
 * If you are looking for a place to alter the behaviour of
 * the 'Comment' type please see the skeleton
 * class 'CommentType'. Modifications to the skeleton
 * file will prevail any subsequent class generation runs.
 *
 * To define new attributes or adjust existing attributes and their
 * default options modify the schema definition file of
 * the 'Comment' type.
 *
 * @see https://github.com/honeybee/trellis
 */

namespace Honeybee\SystemAccount\User\Model\Aggregate\Embed\Base;

use Honeybee\Model\Aggregate\EmbeddedEntityType;
use Trellis\Common\Options;
use Trellis\Runtime\EntityTypeInterface;
use Trellis\Runtime\Attribute\AttributeInterface;

/**
 * Serves as the base class to the 'Comment' type skeleton.
 */
abstract class CommentType extends EmbeddedEntityType
{
    /**
     * Creates a new 'CommentType' instance.
     */
    public function __construct(EntityTypeInterface $parent = null, AttributeInterface $parent_attribute = null)
    {
        parent::__construct(
            'Comment',
            [
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'title',
                    $this,
                    array(
                        'max_length' => 110,
                        'min_length' => 1,
                        'mandatory' => true,
                    ),
                    $parent_attribute
                ),
                new \Trellis\Runtime\Attribute\Textarea\TextareaAttribute(
                    'text',
                    $this,
                    array(
                        'max_length' => 10000,
                    ),
                    $parent_attribute
                ),
            ],
            new Options(
                []
            ),            $parent,
            $parent_attribute
        );
    }

    /**
     * Returns the EntityInterface implementor to use when creating new entities.
     *
     * @return string Fully qualified name of an EntityInterface implementation.
     */
    public static function getEntityImplementor()
    {
        return '\\Honeybee\\SystemAccount\\User\\Model\\Aggregate\\Embed\\Comment';
    }
}
